### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by pgeier** [tkjacobsen/enote#1]
Hey, I  just installed enote on archlinux and have the following problem

```
  % enote pull                                                                                                                                                     0.1
Traceback (most recent call last):
  File "/usr/bin/enote", line 4, in <module>
    enote.main()
  File "/usr/lib/python2.7/site-packages/enote/enote.py", line 187, in main
    config, command, notebook, tags = options.get_config()
  File "/usr/lib/python2.7/site-packages/enote/options.py", line 95, in get_config
    config[opt] = get_option(args, userconfig, profile, opt, opts[opt])
  File "/usr/lib/python2.7/site-packages/enote/options.py", line 72, in get_option
    return defaults[key]
KeyError: 'token'
```

Is the project still active? Do I have evernote to be installed or is nixnote2 sufficient?

**Comment by pgeier** [comment]
Sorry, was a way to fast, did not install the latest release
